// 单日复习报告 - 测试数据
export const mockReviewReport = {
  metadata: {
    report_id: 'REVIEW_20260130_STU001',
    student_id: 'STU001',
    student_name: '小明',
    review_date: '2026-01-30',
    review_time: '20:00-21:00',
    teacher_id: 'TCH001',
    teacher_name: '王老师',
    course_type: 'Model A',
    generated_time: '2026-01-30T22:00:00Z',
  },
  overview: {
    total_review_count: 23,
    review_pass_count: 21,
    review_fail_count: 2,
    review_pass_rate: 91.3,
    review_duration: 18,
    avg_review_time: 47,
  },
  track_distribution: {
    fast_track_count: 15,
    fast_track_pass: 14,
    fast_track_fail: 1,
    standard_track_count: 8,
    standard_track_pass: 7,
    standard_track_fail: 1,
  },
  node_distribution: {
    day1_count: 10,
    day1_pass: 9,
    day3_count: 8,
    day3_pass: 7,
    day7_count: 5,
    day7_pass: 5,
    day15_count: 0,
    day15_pass: 0,
  },
  leapfrog_data: {
    leapfrog_used: 3,
    leapfrog_success: 2,
    leapfrog_fail: 1,
    leapfrog_skip_days: 12,
  },
  funnel_data: {
    funnel_direct_pass: 18,
    funnel_l1_trigger: 3,
    funnel_l1_recover: 2,
    funnel_l2_trigger: 1,
    funnel_l2_recover: 1,
    funnel_l3_trigger: 2,
  },
  question_performance: {
    l4_review_accuracy: 91.3,
    l4_review_avg_time: 5.2,
    l5_accuracy: 87.5,
    l5_avg_time: 8.3,
  },
  review_words: [
    {
      word_id: 'W001',
      word: 'adapt',
      meaning: 'v. 适应',
      review_day: 3,
      track_type: 'fast',
      result: 'pass',
      duration: 12,
      attempts: 1,
      leapfrog_used: false,
      funnel_level: 0,
      l4_correct: true,
      l5_correct: true,
      next_review_day: 15,
    },
  ],
  leapfrog_records: [],
  ai_content: {
    ai_review_summary: '今天复习表现优秀！通过率达91.3%，大部分单词都能快速回忆起来。',
    ai_encouragement: '坚持得很好！连续复习让单词记忆更牢固了。',
    ai_weak_words: ['absorb', 'approach'],
    ai_suggestion: '对于absorb这类双写字母的词，建议多写几遍加深印象。继续保持每日复习的好习惯！',
  },
  progress_comparison: {
    vs_yesterday: {
      pass_rate_change: 3.5,
      duration_change: -2,
    },
    vs_last_week: {
      pass_rate_change: 8.2,
      duration_change: -5,
    },
  },
};
